# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputText.setGeometry(QtCore.QRect(30, 40, 171, 111))
        self.inputText.setObjectName("inputText")
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel.setGeometry(QtCore.QRect(30, 20, 171, 16))
        self.inputLabel.setObjectName("inputLabel")
        self.inputLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel_2.setGeometry(QtCore.QRect(240, 20, 81, 16))
        self.inputLabel_2.setObjectName("inputLabel_2")
        self.keyText = QtWidgets.QLineEdit(self.centralwidget)
        self.keyText.setGeometry(QtCore.QRect(240, 40, 113, 20))
        self.keyText.setObjectName("keyText")
        self.russianOption = QtWidgets.QRadioButton(self.centralwidget)
        self.russianOption.setGeometry(QtCore.QRect(240, 80, 82, 17))
        self.russianOption.setObjectName("russianOption")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.russianOption)
        self.englishOption = QtWidgets.QRadioButton(self.centralwidget)
        self.englishOption.setGeometry(QtCore.QRect(240, 110, 82, 17))
        self.englishOption.setObjectName("englishOption")
        self.buttonGroup.addButton(self.englishOption)
        self.encryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.encryptButton.setGeometry(QtCore.QRect(30, 170, 171, 23))
        self.encryptButton.setObjectName("encryptButton")
        self.outputText = QtWidgets.QLabel(self.centralwidget)
        self.outputText.setGeometry(QtCore.QRect(30, 210, 171, 16))
        self.outputText.setObjectName("outputText")
        self.outputTextW = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.outputTextW.setGeometry(QtCore.QRect(30, 230, 171, 111))
        self.outputTextW.setObjectName("outputTextW")
        self.decryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.decryptButton.setGeometry(QtCore.QRect(30, 350, 171, 23))
        self.decryptButton.setObjectName("decryptButton")
        self.outputTextW_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.outputTextW_2.setGeometry(QtCore.QRect(30, 410, 171, 111))
        self.outputTextW_2.setObjectName("outputTextW_2")
        self.outputText_2 = QtWidgets.QLabel(self.centralwidget)
        self.outputText_2.setGeometry(QtCore.QRect(30, 390, 171, 16))
        self.outputText_2.setObjectName("outputText_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №1"))
        self.inputLabel.setText(_translate("MainWindow", "Исходное сообщение:"))
        self.inputLabel_2.setText(_translate("MainWindow", "Ключ:"))
        self.russianOption.setText(_translate("MainWindow", "Русский"))
        self.englishOption.setText(_translate("MainWindow", "Английский"))
        self.encryptButton.setText(_translate("MainWindow", "Зашифровать"))
        self.outputText.setText(_translate("MainWindow", "Зашифрованное сообщение:"))
        self.decryptButton.setText(_translate("MainWindow", "Расшифровать"))
        self.outputText_2.setText(_translate("MainWindow", "Расшифрованное сообщение:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
